---
# file: tasks/vars.yml

- name: vars - load per operating system variables
  include_vars: "{{item}}"
  with_first_found:
    - paths:
      - "vars/"
    - files:
      - "{{ansible_distribution|lower}}-{{ansible_distribution_version|lower}}-{{ansible_machine}}.yml"       # centos-6.4-i386.yml ubuntu-16.04-x86_64.yml
      - "{{ansible_distribution|lower}}-{{ansible_distribution_version|lower}}.yml"                           # centos-6.4.yml ubuntu-16.04.yml
      - "{{ansible_distribution|lower}}-{{ansible_distribution_major_version|lower}}-{{ansible_machine}}.yml" # centos-6-i386.yml ubuntu-16-x86_64.yml
      - "{{ansible_distribution|lower}}-{{ansible_distribution_major_version|lower}}.yml"                     # centos-6.yml ubuntu-16.yml
      - "{{ansible_os_family|lower}}-{{ansible_distribution_version|lower}}-{{ansible_machine}}.yml"          # redhat-6.4-i386.yml debian-8.5-x86_64.yml
      - "{{ansible_os_family|lower}}-{{ansible_distribution_version|lower}}.yml"                              # redhat-6.4.yml debian-8.5.yml
      - "{{ansible_os_family|lower}}-{{ansible_distribution_major_version|lower}}-{{ansible_machine}}.yml"    # redhat-6-i386.yml debian-8-x86_64.yml
      - "{{ansible_os_family|lower}}-{{ansible_distribution_major_version|lower}}.yml"                        # redhat-6.yml debian-8.yml
      - "{{ansible_distribution|lower}}-{{ansible_machine}}.yml"                                              # centos-i386.yml ubuntu-x86_64.yml
      - "{{ansible_distribution|lower}}.yml"                                                                  # centos.yml ubuntu.yml
      - "{{ansible_os_family|lower}}-{{ansible_machine}}.yml"                                                 # redhat-i386.yml debian-x86_64.yml
      - "{{ansible_os_family|lower}}.yml"                                                                     # redhat.yml debian.yml
      - "{{ansible_system|lower}}-{{ansible_machine}}.yml"                                                    # linux-i386.yml linux-x86_64.yml
      - "{{ansible_system|lower}}.yml"                                                                        # linux.yml
      - "default.yml"                                                                                         # default.yml
      skip: true

- name: vars - override with local variables
  include_vars: "{{item}}"
  with_first_found:
    - paths:
      - "vars/"
    - files:
      - "local.yml"
      skip: true
