---
# file: tasks/vars.yml

- name: load variables for specific operating system
  include_vars: "{{item}}"
  with_first_found:
    - "vars/{{ansible_distribution|lower}}-{{ansible_distribution_version|lower}}-{{ansible_machine}}.yml"       # centos-6.4-i386.yml ubuntu-16.04-x86_64.yml
    - "vars/{{ansible_distribution|lower}}-{{ansible_distribution_version|lower}}.yml"                           # centos-6.4.yml ubuntu-16.04.yml
    - "vars/{{ansible_distribution|lower}}-{{ansible_distribution_major_version|lower}}-{{ansible_machine}}.yml" # centos-6-i386.yml ubuntu-16-x86_64.yml
    - "vars/{{ansible_distribution|lower}}-{{ansible_distribution_major_version|lower}}.yml"                     # centos-6.yml ubuntu-16.yml
    - "vars/{{ansible_os_family|lower}}-{{ansible_distribution_version|lower}}-{{ansible_machine}}.yml"          # redhat-6.4-i386.yml debian-8.5-x86_64.yml
    - "vars/{{ansible_os_family|lower}}-{{ansible_distribution_version|lower}}.yml"                              # redhat-6.4.yml debian-8.5.yml
    - "vars/{{ansible_os_family|lower}}-{{ansible_distribution_major_version|lower}}-{{ansible_machine}}.yml"    # redhat-6-i386.yml debian-8-x86_64.yml
    - "vars/{{ansible_os_family|lower}}-{{ansible_distribution_major_version|lower}}.yml"                        # redhat-6.yml debian-8.yml
    - "vars/{{ansible_distribution|lower}}-{{ansible_machine}}.yml"                                              # centos-i386.yml ubuntu-x86_64.yml
    - "vars/{{ansible_distribution|lower}}.yml"                                                                  # centos.yml ubuntu.yml
    - "vars/{{ansible_os_family|lower}}-{{ansible_machine}}.yml"                                                 # redhat-i386.yml debian-x86_64.yml
    - "vars/{{ansible_os_family|lower}}.yml"                                                                     # redhat.yml debian.yml
    - "vars/{{ansible_system|lower}}-{{ansible_machine}}.yml"                                                    # linux-i386.yml linux-x86_64.yml
    - "vars/{{ansible_system|lower}}.yml"                                                                        # linux.yml
    - "vars/default.yml"                                                                                         # default.yml

- name: load common variables
  include_vars: main.yml
